# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

use_frameworks!
inhibit_all_warnings!

target 'AppInTheAirWidgetSDK' do
  pod 'FLKAutoLayout', '~> 0.2.1'
end
